version: "2"
services:
  db:
    build: ./db
    image: vnopenroads/openroads-vn-db:latest
    container_name: vn-api-db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=openroads

  api:
    build: .
    image: vnopenroads/openroads-vn-api:latest
    env_file: .env
    depends_on:
      - db
      - redis
    ports:
      - "80:4000"
    environment:
      - DATABASE_URL=postgres://postgres@db:5432/openroads
      - REDIS_URL=redis://redis:6379

  vn-tiler:
    image: vnopenroads/openroads-vn-tiler:latest
    env_file: .env
    command: ./cron.sh
    environment:
      - S3_TEMPLATE=s3://openroads-vn-tiles/tiles/{z}/{x}/{y}.vector.pbf
      - S3_DUMP_BUCKET=openroads-vn-dumps
      - DATABASE_URL=postgres://postgres@db:5432/openroads

  tilemap:
    image: vnopenroads/openroads-vn-tilemap:latest
    env_file: .env
    ports:
      - "3000:3000"
    environment:
      - BUCKET_URL=http://openroads-vn-tiles.s3-website-us-east-1.amazonaws.com/tiles

  redis:
    container_name: vn-redis
    image: redis
    command: redis-server

  deploy:
    image: vnopenroads/openroads-vn-api:latest
    command: node_modules/.bin/kes cf update -k aws/app --env-file .env
    env_file: .env
